version: '3.8'
name: 'question-ddd'
services:
  postgres:
    image: docker.io/bitnami/postgresql:15.2.0-debian-11-r30
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: exec pg_isready -U "postgres" -d "dbname=postgres"
      retries: 5
    environment:
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USERNAME=postgres
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - pgsql:/bitnami/postgresql
      - ./docker/postgres/db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql:rw
    networks:
      - internals

networks:
  internals: {}

volumes:
  pgsql:
    driver: local
  gocache:
  go:
