# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTdiMTg2NzllZWEyMzkxYjM1ZGEzYmRmZDk3YjNmNzk5YTQxY2ZkODgxOGRiZDNiMTdiMDAzODVmZDJiNTE4NTgxNmNlOGE4NjhhYmExOTMzODgwMDU0OWU3NTFjYTI0YWU4ZjkxNjc5ZTMyOTQzODE2YjA0ODQxY2ViMTEyNzg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
