services:
  answercontext:
    image: answercontext
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://answercontext-postgresql:5432/AnswerContext
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://answercontext-postgresql:5432/AnswerContext
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  answercontext-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=AnswerContext
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  evaluationcontext:
    image: evaluationcontext
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://evaluationcontext-postgresql:5432/EvaluationContext
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://evaluationcontext-postgresql:5432/EvaluationContext
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  evaluationcontext-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=EvaluationContext
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  questioncontext:
    image: questioncontext
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://questioncontext-postgresql:5432/QuestionContext
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://questioncontext-postgresql:5432/QuestionContext
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  questioncontext-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=QuestionContext
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  sendquestioncontext:
    image: sendquestioncontext
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sendquestioncontext-postgresql:5432/SendQuestionContext
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://sendquestioncontext-postgresql:5432/SendQuestionContext
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  sendquestioncontext-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=SendQuestionContext
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  skillcontext:
    image: skillcontext
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://skillcontext-postgresql:5432/SkillContext
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://skillcontext-postgresql:5432/SkillContext
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  skillcontext-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=SkillContext
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  statcontext:
    image: statcontext
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statcontext-postgresql:5432/StatContext
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://statcontext-postgresql:5432/StatContext
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  statcontext-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=StatContext
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  usermanagementcontext:
    image: usermanagementcontext
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://usermanagementcontext-postgresql:5432/UserManagementContext
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://usermanagementcontext-postgresql:5432/UserManagementContext
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  usermanagementcontext-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=UserManagementContext
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  gateway:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_R2DBC_URL=r2dbc:postgresql://gateway-postgresql:5432/gateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway
      - JHIPSTER_SLEEP=60
    ports:
      - "8087:8080"
  gateway-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
